"""Added 2 pydantic models

Revision ID: 3ba3814f2afd
Revises: d8dc3ec3f44f
Create Date: 2025-05-26 20:20:55.386783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ba3814f2afd'
down_revision: Union[str, None] = 'd8dc3ec3f44f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('symbol', sa.Column('eod_id', sa.String(length=15), nullable=True))
    op.drop_column('symbol', 'css_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('symbol', sa.Column('css_id', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    op.drop_column('symbol', 'eod_id')
    # ### end Alembic commands ###
