"""Add notes column to eod_data_symbol

Revision ID: 7b2468d9723d
Revises: e5130d5a9676
Create Date: 2025-05-18 16:02:09.761305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b2468d9723d'
down_revision: Union[str, None] = 'e5130d5a9676'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eod_data_symbol', sa.Column('notes', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eod_data_symbol', 'notes')
    # ### end Alembic commands ###
