"""Add options tables

Revision ID: 9ad8b0c6358c
Revises: 7b2468d9723d
Create Date: 2025-05-18 18:30:21.649968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ad8b0c6358c'
down_revision: Union[str, None] = '7b2468d9723d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('options_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('underlying_symbol', sa.String(length=10), nullable=False),
    sa.Column('option_symbol', sa.String(length=30), nullable=False),
    sa.Column('contract_type', sa.String(length=4), nullable=False),
    sa.Column('strike_price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=False),
    sa.Column('is_index_option', sa.Boolean(), nullable=False),
    sa.Column('date_available', sa.Date(), nullable=True),
    sa.Column('days_to_expiration', sa.SmallInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_contracts_active', 'options_contracts', ['is_active'], unique=False)
    op.create_index('idx_contracts_chain_lookup', 'options_contracts', ['underlying_symbol', 'expiration_date', 'contract_type'], unique=False)
    op.create_index('idx_contracts_underlying_expiry', 'options_contracts', ['underlying_symbol', 'expiration_date'], unique=False)
    op.create_index('idx_contracts_underlying_strike', 'options_contracts', ['underlying_symbol', 'strike_price'], unique=False)
    op.create_index(op.f('ix_options_contracts_expiration_date'), 'options_contracts', ['expiration_date'], unique=False)
    op.create_index(op.f('ix_options_contracts_option_symbol'), 'options_contracts', ['option_symbol'], unique=True)
    op.create_index(op.f('ix_options_contracts_strike_price'), 'options_contracts', ['strike_price'], unique=False)
    op.create_index(op.f('ix_options_contracts_underlying_symbol'), 'options_contracts', ['underlying_symbol'], unique=False)
    op.create_table('options_market_data',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('data_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('underlying_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('bid', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('ask', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('bid_size', sa.Integer(), nullable=True),
    sa.Column('ask_size', sa.Integer(), nullable=True),
    sa.Column('last_price', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('last_trade_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_trade_size', sa.Integer(), nullable=True),
    sa.Column('mark_price', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('open_interest', sa.Integer(), nullable=True),
    sa.Column('delta', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('gamma', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('theta', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('vega', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('rho', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('implied_volatility', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('days_to_expiration', sa.SmallInteger(), nullable=True),
    sa.Column('in_the_money', sa.Boolean(), nullable=True),
    sa.Column('near_the_money', sa.Boolean(), nullable=True),
    sa.Column('is_tradeable', sa.Boolean(), nullable=True),
    sa.Column('quote_condition', sa.String(length=5), nullable=True),
    sa.Column('data_source', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['options_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_market_data_contract_time', 'options_market_data', ['contract_id', 'data_timestamp'], unique=False)
    op.create_index('idx_market_data_latest', 'options_market_data', ['contract_id', 'data_timestamp'], unique=False, postgresql_using='btree')
    op.create_index('idx_market_data_timestamp', 'options_market_data', ['data_timestamp'], unique=False)
    op.create_index('idx_market_data_tradeable', 'options_market_data', ['is_tradeable'], unique=False, postgresql_where=sa.text('is_tradeable = true'))
    op.create_index('idx_market_data_volume', 'options_market_data', ['volume'], unique=False)
    op.create_index(op.f('ix_options_market_data_contract_id'), 'options_market_data', ['contract_id'], unique=False)
    op.create_index(op.f('ix_options_market_data_data_timestamp'), 'options_market_data', ['data_timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_options_market_data_data_timestamp'), table_name='options_market_data')
    op.drop_index(op.f('ix_options_market_data_contract_id'), table_name='options_market_data')
    op.drop_index('idx_market_data_volume', table_name='options_market_data')
    op.drop_index('idx_market_data_tradeable', table_name='options_market_data', postgresql_where=sa.text('is_tradeable = true'))
    op.drop_index('idx_market_data_timestamp', table_name='options_market_data')
    op.drop_index('idx_market_data_latest', table_name='options_market_data', postgresql_using='btree')
    op.drop_index('idx_market_data_contract_time', table_name='options_market_data')
    op.drop_table('options_market_data')
    op.drop_index(op.f('ix_options_contracts_underlying_symbol'), table_name='options_contracts')
    op.drop_index(op.f('ix_options_contracts_strike_price'), table_name='options_contracts')
    op.drop_index(op.f('ix_options_contracts_option_symbol'), table_name='options_contracts')
    op.drop_index(op.f('ix_options_contracts_expiration_date'), table_name='options_contracts')
    op.drop_index('idx_contracts_underlying_strike', table_name='options_contracts')
    op.drop_index('idx_contracts_underlying_expiry', table_name='options_contracts')
    op.drop_index('idx_contracts_chain_lookup', table_name='options_contracts')
    op.drop_index('idx_contracts_active', table_name='options_contracts')
    op.drop_table('options_contracts')
    # ### end Alembic commands ###
